### ISSUE TITLE
Remove .vscode//sftp.json?

### ISSUE THREAD

**Issue by arche-dev** [BiizoNinja/shrek-bot#28]
`.vscode//sftp.json` looks like some authentication for hosting the bot.

You can remove `.vscode//sftp.json` and add this to `.gitignore`:

```gitignore
node_modules
.env
.vscode//sftp.json
```

https://git-scm.com/docs/gitignore

Then you can add it back (locally, not on github) and `git` should ignore the file :p

**Comment by BiizoNinja** [comment]
I'm not using bluefoxhost anyway, so there is no needing of ignoring. I'll just delete

**Comment by arche-dev** [comment]
> I'm not using bluefoxhost anyway, so there is no needing of ignoring. I'll just delete

Ok sure
